"""empty message

Revision ID: 6ee0a90d1f2f
Revises: 
Create Date: 2021-03-26 13:47:03.819882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ee0a90d1f2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'admin', ['email'])
    op.alter_column('goods', 'right',
               existing_type=mysql.VARCHAR(length=4),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('subcat', 'addtime',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('supercat', 'addtime',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'right',
               existing_type=mysql.VARCHAR(length=4),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'right',
               existing_type=mysql.VARCHAR(length=4),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('supercat', 'addtime',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('subcat', 'addtime',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('goods', 'right',
               existing_type=mysql.VARCHAR(length=4),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_constraint(None, 'admin', type_='unique')
    # ### end Alembic commands ###
